(ns otjni.core
  (:use [clj-native.direct :only [defclib loadlib]]))

(defclib
  otapi-lib
  (:libname "otapi")
  (:functions
   (OT_API_Init [constchar*] int)
   (OT_API_LoadWallet [constchar*] int)
   (OT_API_CreateNym [] constchar*)
   (OT_API_AddServerContract [constchar*] int)
   (OT_API_AddAssetContract [constchar*] int)
   (OT_API_GetServerCount [] int)
   (OT_API_GetAssetTypeCount [] int)
   (OT_API_GetAccountCount [] int)
   (OT_API_GetNymCount [] int)
   (OT_API_GetServer_ID [int] constchar*)
   (OT_API_GetServer_Name [constchar*] constchar*)
   (OT_API_GetAssetType_ID [int] constchar*)
   (OT_API_GetAssetType_Name [constchar*] constchar*)
   (OT_API_GetAccountWallet_ID [int] constchar*)
   (OT_API_GetAccountWallet_Name [constchar*] constchar*)
   (OT_API_GetAccountWallet_Balance [constchar*] constchar*)
   (OT_API_GetAccountWallet_Type [constchar*] constchar*)
   (OT_API_GetAccountWallet_AssetTypeID [constchar*] constchar*)
   (OT_API_GetNym_TransactionNumCount [constchar* constchar*] int)
   (OT_API_GetNym_ID [int] constchar*)
   (OT_API_GetNym_Name [constchar*] constchar*)
   (OT_API_SetNym_Name [constchar* constchar* constchar*] int)
   (OT_API_SetAccountWallet_Name [constchar* constchar* constchar*] int)
   (OT_API_SetAssetType_Name [constchar* constchar*] int)
   (OT_API_SetServer_Name [constchar* constchar*] int)
   (OT_API_VerifyAndRetrieveXMLContents [constchar* constchar*] constchar*)
   (OT_API_WriteCheque [constchar* constchar* constchar* constchar* constchar* constchar* constchar* constchar*] constchar*)
   (OT_API_WritePaymentPlan [constchar* constchar* constchar* constchar* constchar* constchar* constchar* constchar* constchar* constchar* constchar* constchar* constchar* constchar* constchar*] constchar*)
   (OT_API_LoadUserPubkey [constchar*] constchar*)
   (OT_API_LoadPubkey [constchar*] constchar*)
   (OT_API_VerifyUserPrivateKey [constchar*] int)
   (OT_API_LoadPurse [constchar* constchar*] constchar*)
   (OT_API_LoadMint [constchar* constchar*] constchar*)
   (OT_API_LoadAssetContract [constchar*] constchar*)
   (OT_API_IsBasketCurrency [constchar*] int)
   (OT_API_Basket_GetMemberCount [constchar*] int)
   (OT_API_Basket_GetMemberType [constchar* int] constchar*)
   (OT_API_Basket_GetMinimumTransferAmount [constchar*] constchar*)
   (OT_API_Basket_GetMemberMinimumTransferAmount [constchar* int] constchar*)
   (OT_API_LoadAssetAccount [constchar* constchar* constchar*] constchar*)
   (OT_API_LoadInbox [constchar* constchar* constchar*] constchar*)
   (OT_API_LoadOutbox [constchar* constchar* constchar*] constchar*)
   (OT_API_Ledger_GetCount [constchar* constchar* constchar* constchar*] int)
   (OT_API_Ledger_CreateResponse [constchar* constchar* constchar* constchar*] constchar*)
   (OT_API_Ledger_GetTransactionByIndex [constchar* constchar* constchar* constchar* int] constchar*)
   (OT_API_Ledger_GetTransactionByID [constchar* constchar* constchar* constchar* constchar*] constchar*)
   (OT_API_Ledger_GetTransactionIDByIndex [constchar* constchar* constchar* constchar* int] constchar*)
   (OT_API_Ledger_AddTransaction [constchar* constchar* constchar* constchar* constchar*] constchar*)
   (OT_API_Transaction_CreateResponse [constchar* constchar* constchar* constchar* constchar* int] constchar*)
   (OT_API_Ledger_FinalizeResponse [constchar* constchar* constchar* constchar* int] constchar*)
   (OT_API_Transaction_GetType [constchar* constchar* constchar* constchar*] constchar*)
   (OT_API_Transaction_GetVoucher [constchar* constchar* constchar* constchar*] constchar*)
   (OT_API_Transaction_GetSuccess [constchar* constchar* constchar* constchar*] int)
   (OT_API_Pending_GetFromUserID [constchar* constchar* constchar* constchar*] constchar*)
   (OT_API_Pending_GetFromAcctID [constchar* constchar* constchar* constchar*] constchar*)
   (OT_API_Pending_GetNote [constchar* constchar* constchar* constchar*] constchar*)
   (OT_API_Pending_GetAmount [constchar* constchar* constchar* constchar*] constchar*)
   (OT_API_Pending_GetReferenceToNum [constchar* constchar* constchar* constchar*] constchar*)
   (OT_API_Purse_GetTotalValue [constchar* constchar* constchar*] constchar*)
   (OT_API_checkServerID [constchar* constchar*])
   (OT_API_createUserAccount [constchar* constchar*])
   (OT_API_checkUser [constchar* constchar* constchar*])
   (OT_API_sendUserMessage [constchar* constchar* constchar* constchar* constchar*])
   (OT_API_getRequest [constchar* constchar*])
   (OT_API_getTransactionNumber [constchar* constchar*])
   (OT_API_issueAssetType [constchar* constchar* constchar*])
   (OT_API_getContract [constchar* constchar* constchar*])
   (OT_API_getMint [constchar* constchar* constchar*])
   (OT_API_createAssetAccount [constchar* constchar* constchar*])
   (OT_API_getAccount [constchar* constchar* constchar*])
   (OT_API_GenerateBasketCreation [constchar* constchar*] constchar*)
   (OT_API_AddBasketCreationItem [constchar* constchar* constchar* constchar*] constchar*)
   (OT_API_issueBasket [constchar* constchar* constchar*])
   (OT_API_GenerateBasketExchange [constchar* constchar* constchar* constchar* int] constchar*)
   (OT_API_AddBasketExchangeItem [constchar* constchar* constchar* constchar* constchar*] constchar*)
   (OT_API_exchangeBasket [constchar* constchar* constchar* constchar* int])
   (OT_API_notarizeWithdrawal [constchar* constchar* constchar* constchar*])
   (OT_API_notarizeDeposit [constchar* constchar* constchar* constchar*])
   (OT_API_notarizeTransfer [constchar* constchar* constchar* constchar* constchar* constchar*])
   (OT_API_getInbox [constchar* constchar* constchar*])
   (OT_API_getOutbox [constchar* constchar* constchar*])
   (OT_API_getNymbox [constchar* constchar*])
   (OT_API_LoadNymbox [constchar* constchar*] constchar*)
   (OT_API_processInbox [constchar* constchar* constchar* constchar*])
   (OT_API_withdrawVoucher [constchar* constchar* constchar* constchar* constchar* constchar*])
   (OT_API_depositCheque [constchar* constchar* constchar* constchar*])
   (OT_API_depositPaymentPlan [constchar* constchar* constchar*])
   (OT_API_issueMarketOffer [constchar* constchar* constchar* constchar* constchar* constchar* constchar* constchar* constchar* constchar* int])
   (OT_API_PopMessageBuffer [] constchar*)
   (OT_API_FlushMessageBuffer [])
   (OT_API_Message_GetCommand [constchar*] constchar*)
   (OT_API_Message_GetSuccess [constchar*] int)
   (OT_API_Message_GetLedger [constchar*] constchar*)
   (OT_API_Message_GetNewAssetTypeID [constchar*] constchar*)
   (OT_API_Message_GetNewIssuerAcctID [constchar*] constchar*)))
